use_frameworks!

target 'CZImagePreviewer_Example' do
  pod 'CZImagePreviewer', :path => '../'
  pod 'Masonry'
  pod 'AFNetworking'
  
  target 'CZImagePreviewer_Tests' do
    inherit! :search_paths

    
  end
end
